name: underwater_cv
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - absl-py=2.3.1=pyhd8ed1ab_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - aom=3.6.0=h313beb8_0
  - atk-1.0=2.38.0=hcb7b3dd_1
  - blas=1.0=openblas
  - brotli=1.2.0=hca488c2_0
  - brotli-bin=1.2.0=hce9b42c_0
  - brotlicffi=1.0.9.2=py310h50f4ffc_2
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.4=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py310h73c2a22_1
  - charset-normalizer=3.4.4=py310hca03da5_0
  - cloudpickle=3.1.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h7f4e7e6_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - dataclasses=0.8=pyhc8e2a94_3
  - dav1d=1.2.1=h80987f9_0
  - detectron2=0.6=cpu_py310h19b2e79_15
  - expat=2.7.3=h982b769_0
  - filelock=3.20.0=py310hca03da5_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h29935d0_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py310hf4fd40f_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_2
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.10=h969f7ef_2
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - glib=2.84.4=h863a760_0
  - glib-tools=2.84.4=hff4a405_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py310h5c1b81f_0
  - graphite2=1.3.14=hc377ac9_1
  - graphviz=7.1.0=h4f8fbd6_0
  - grpcio=1.74.1=py310h1e75bc9_1
  - gtk2=2.24.33=h57013de_2
  - gts=0.7.6=he42f4ea_4
  - harfbuzz=10.2.0=he637ebf_1
  - hydra-core=1.3.2=pyhd8ed1ab_1
  - icu=73.2=hc8870d7_0
  - idna=3.11=py310hca03da5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iopath=0.1.9=pyhd8ed1ab_0
  - jinja2=3.1.6=py310hca03da5_0
  - jpeg=9f=h2f69dba_0
  - kaldi=5.5.1112=cpu_h2c2f6ee_1
  - kiwisolver=1.4.9=py310h563d721_2
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libavif=1.1.1=h80987f9_0
  - libblas=3.9.0=1_h2ec9a88_netlib
  - libbrotlicommon=1.2.0=h87ba0bc_0
  - libbrotlidec=1.2.0=h95a88de_0
  - libbrotlienc=1.2.0=hb1b9735_0
  - libcblas=3.9.0=11_h742a510_netlib
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.13.3=hce30654_1
  - libfreetype6=2.13.3=h1d14073_1
  - libgd=2.3.3=hd3b0a14_4
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.84.4=h7a3292d_0
  - libgrpc=1.74.1=h3063b79_1
  - libiconv=1.16=h80987f9_3
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - liblapack=3.9.0=11_hd5e45d6_netlib
  - liblapacke=3.9.0=11_h5bf4901_netlib
  - libltdl=2.4.3a=h286801f_0
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - libprotobuf=6.31.1=h658db43_2
  - libre2-11=2025.11.05=h91c62da_0
  - librsvg=2.58.0=hb3d354b_1
  - libsqlite=3.51.0=h9a5124b_0
  - libtiff=4.7.0=h91aec0a_0
  - libtool=2.5.4=h286801f_0
  - libtorch=2.7.1=cpu_generic_h8557a0d_4
  - libuv=1.51.0=h6caf38d_1
  - libwebp=1.3.2=hf40cdb4_1
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.5=h4a912ad_0
  - lz4-c=1.9.4=h313beb8_1
  - markdown=3.10=pyhd8ed1ab_0
  - markupsafe=3.0.2=py310h80987f9_0
  - matplotlib-base=3.10.6=py310h0181960_1
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py310hca03da5_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - networkx=3.4.2=py310hca03da5_0
  - nomkl=1.0=h5ca1d4c_0
  - numpy=1.26.4=py310h901140f_1
  - numpy-base=1.26.4=py310hae06d03_1
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openfst=1.8.3=h950e60b_3
  - openssl=3.5.4=h5503f6c_0
  - optree=0.17.0=py310h0e897d2_2
  - packaging=25.0=pyh29332c3_1
  - pango=1.50.14=hcf40dda_2
  - pcre2=10.46=h1dacb4a_0
  - pillow=12.0.0=py310he2d6fe4_1
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h09dc60e_0
  - portalocker=3.2.0=py310hbe9552e_1
  - protobuf=6.31.1=py310hc33aa15_2
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycocotools=2.0.10=py310hfdc7867_1
  - pycparser=2.23=py310hca03da5_0
  - pydot=4.0.1=py310hbe9552e_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=py310hca03da5_1
  - python=3.10.16=h2ecfa3e_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pytorch=2.7.1=cpu_generic_py310_h20f5f40_4
  - pyyaml=6.0.2=py310h80987f9_0
  - qhull=2020.2=h420ef59_5
  - re2=2025.11.05=h64b956e_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py310hca03da5_1
  - setuptools=80.9.0=py310hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - sqlite=3.51.0=hab6afd1_0
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tensorboard=2.20.0=pyhe01879c_0
  - tensorboard-data-server=0.7.0=py310h0305fc1_3
  - termcolor=3.2.0=pyhd8ed1ab_0
  - tk=8.6.15=hcd8a7d5_0
  - torchaudio=2.7.1=cpu_py310h5814d1f_1
  - torchvision=0.15.2=cpu_py310h31aa045_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=py310hca03da5_0
  - typing_extensions=4.15.0=py310hca03da5_0
  - unicodedata2=17.0.0=py310hfe3a0ae_0
  - urllib3=2.5.0=py310hca03da5_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - yacs=0.1.8=pyh29332c3_2
  - yaml=0.2.5=h1a28f6b_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - anyio==4.11.0
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - comm==0.2.3
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fqdn==1.5.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - ipykernel==7.1.0
      - ipython==8.37.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - lark==1.3.1
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - overrides==7.7.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.5.0
      - polars==1.35.1
      - polars-runtime-32==1.35.1
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pyzmq==27.1.0
      - referencing==0.37.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.28.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - send2trash==1.8.3
      - simsimd==6.5.3
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - stringzilla==4.2.3
      - sympy==1.13.1
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tomli==2.3.0
      - tornado==6.5.2
      - traitlets==5.14.3
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ultralytics==8.3.225
      - ultralytics-thop==2.0.18
      - uri-template==1.3.0
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
prefix: /opt/anaconda3/envs/underwater_cv
